# Created with podman-5.6.2
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: haproxy
  name: haproxy
spec:
  containers:
  - args:
    - haproxy
    - -f
    - /usr/local/etc/haproxy/haproxy.cfg
    env:
    - name: TERM
      value: xterm
    - name: HTTPLOG_JSON
      value: "%{+json}o %(client_ip)ci %(client_port)cp %(request_date)tr %(fe_name_transport)ft %(be_name)b %(server_name)s %(time_request)TR %(time_wait)Tw %(time_connect)Tc %(time_response)Tr/%(time_active)Ta %(status_code)ST %(bytes_read)B %(captured_request_cookie)CC %(captured_response_cookie)CS %(termination_state_cookie)tsc %(actconn)ac %(feconn)fc %(beconn)bc %(srv_conn)sc %(retries)rc %(srv_queue)sq %(backend_queue)bq %(captured_request_headers)hr %(captured_response_headers)hs %(http_request){+Q}r"
    image: localhost/lb:latest
    name: lb
    ports:
    - containerPort: 8181
      hostPort: 8181
      name: stats
    - containerPort: 8383
      hostPort: 8383
    securityContext: {}
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TERM
      value: xterm
    image: localhost/web:latest
    name: web1
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TERM
      value: xterm
    image: localhost/web:latest
    name: web2
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TERM
      value: xterm
    image: localhost/web:latest
    name: web3
    tty: true
