---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: haproxy
  name: haproxy
spec:
  containers:
  - args:
    - haproxy
    - -f
    - /usr/local/etc/haproxy/haproxy.cfg
    env:
    - name: TERM
      value: xterm
    - name: HTTPLOG_JSON
      value: "%{+json}o %(client_ip)ci %(client_port)cp %(request_date)tr %(fe_name_transport)ft %(be_name)b %(server_name)s %(time_request)TR %(time_wait)Tw %(time_connect)Tc %(time_response)Tr/%(time_active)Ta %(status_code)ST %(bytes_read)B %(captured_request_cookie)CC %(captured_response_cookie)CS %(termination_state_cookie)tsc %(actconn)ac %(feconn)fc %(beconn)bc %(srv_conn)sc %(retries)rc %(srv_queue)sq %(backend_queue)bq %(captured_request_headers)hr %(captured_response_headers)hs %(http_request){+Q}r"
    image: lb
    name: lb
    ports:
    - containerPort: 8181
      hostPort: 8181
      name: stats
    - containerPort: 8383
      hostPort: 8383
    - containerPort: 9999
      hostPort: 9999
      name: api
    securityContext: {}
    volumeMounts:
      - name: haproxy-cfg-vol
        mountPath: /usr/local/etc/haproxy/
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TERM
      value: xterm
    - name: NGINX_PORT
      value: 8391
    image: web
    name: web1
    volumeMounts:
      - name: nginx-cfg-vol
        mountPath: /etc/nginx/
      - name: nginx-tmpl-vol
        mountPath: /etc/nginx/templates/
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TERM
      value: xterm
    - name: NGINX_PORT
      value: 8392
    image: web
    name: web2
    volumeMounts:
      - name: nginx-cfg-vol
        mountPath: /etc/nginx/
      - name: nginx-tmpl-vol
        mountPath: /etc/nginx/templates/
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TERM
      value: xterm
    - name: NGINX_PORT
      value: 8393
    image: web
    name: web3
    volumeMounts:
      - name: nginx-cfg-vol
        mountPath: /etc/nginx/
      - name: nginx-tmpl-vol
        mountPath: /etc/nginx/templates/
    tty: true
  volumes:
    - name: haproxy-cfg-vol
      configMap:
        name: haproxy-cfg
    - name: nginx-cfg-vol
      configMap:
        name: nginx-cfg
    - name: nginx-tmpl-vol
      configMap:
        name: nginx-tmpl
